### ISSUE TITLE
IO board mod on the IO board 6.1

### ISSUE THREAD

**Issue by L4ZZZ** [blue212/SNAC#1]
Hi,
I just wanted to know if I have to make the 7 pin mod on the IO board 6.1 in order to use a SEGA controller ?

**Comment by Lessthan0tom** [comment]
The 6.1 IO board adds support for the 7th pin. You need to connect to two pins labeled "jumper" on the SNAC together for the 7th pin to work also

**Comment by L4ZZZ** [comment]
And I suppose i have to connect those pins on the IO board too, right ?
![Annotation 2020-05-31 233951](https://user-images.githubusercontent.com/65264977/83363280-8631f980-a398-11ea-9a6f-ac9563c93c88.png)

**Comment by Lessthan0tom** [comment]
I beleive that is correct. Looking at the board visually, you want to jump
the middle pin to the one labeled IO on the pins near the port. I am not
familiar with the schematic but it looks like that would be the position
connecting 2 and 3 at a glance.

**Comment by L4ZZZ** [comment]
Alright, thanks for your help.
